// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// DeleteWorkloadClusterOKCode is the HTTP code returned for type DeleteWorkloadClusterOK
const DeleteWorkloadClusterOKCode int = 200

/*DeleteWorkloadClusterOK Cluster deletion submitted.

swagger:response deleteWorkloadClusterOK
*/
type DeleteWorkloadClusterOK struct {
}

// NewDeleteWorkloadClusterOK creates DeleteWorkloadClusterOK with default headers values
func NewDeleteWorkloadClusterOK() *DeleteWorkloadClusterOK {

	return &DeleteWorkloadClusterOK{}
}

// WriteResponse to the client
func (o *DeleteWorkloadClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteWorkloadClusterBadRequestCode is the HTTP code returned for type DeleteWorkloadClusterBadRequest
const DeleteWorkloadClusterBadRequestCode int = 400

/*DeleteWorkloadClusterBadRequest Bad request

swagger:response deleteWorkloadClusterBadRequest
*/
type DeleteWorkloadClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWorkloadClusterBadRequest creates DeleteWorkloadClusterBadRequest with default headers values
func NewDeleteWorkloadClusterBadRequest() *DeleteWorkloadClusterBadRequest {

	return &DeleteWorkloadClusterBadRequest{}
}

// WithPayload adds the payload to the delete workload cluster bad request response
func (o *DeleteWorkloadClusterBadRequest) WithPayload(payload *models.Error) *DeleteWorkloadClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workload cluster bad request response
func (o *DeleteWorkloadClusterBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadClusterUnauthorizedCode is the HTTP code returned for type DeleteWorkloadClusterUnauthorized
const DeleteWorkloadClusterUnauthorizedCode int = 401

/*DeleteWorkloadClusterUnauthorized Incorrect credentials

swagger:response deleteWorkloadClusterUnauthorized
*/
type DeleteWorkloadClusterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWorkloadClusterUnauthorized creates DeleteWorkloadClusterUnauthorized with default headers values
func NewDeleteWorkloadClusterUnauthorized() *DeleteWorkloadClusterUnauthorized {

	return &DeleteWorkloadClusterUnauthorized{}
}

// WithPayload adds the payload to the delete workload cluster unauthorized response
func (o *DeleteWorkloadClusterUnauthorized) WithPayload(payload *models.Error) *DeleteWorkloadClusterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workload cluster unauthorized response
func (o *DeleteWorkloadClusterUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteWorkloadClusterInternalServerErrorCode is the HTTP code returned for type DeleteWorkloadClusterInternalServerError
const DeleteWorkloadClusterInternalServerErrorCode int = 500

/*DeleteWorkloadClusterInternalServerError Internal server error

swagger:response deleteWorkloadClusterInternalServerError
*/
type DeleteWorkloadClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteWorkloadClusterInternalServerError creates DeleteWorkloadClusterInternalServerError with default headers values
func NewDeleteWorkloadClusterInternalServerError() *DeleteWorkloadClusterInternalServerError {

	return &DeleteWorkloadClusterInternalServerError{}
}

// WithPayload adds the payload to the delete workload cluster internal server error response
func (o *DeleteWorkloadClusterInternalServerError) WithPayload(payload *models.Error) *DeleteWorkloadClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workload cluster internal server error response
func (o *DeleteWorkloadClusterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkloadClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
