// Code generated by go-swagger; DO NOT EDIT.

package docker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ExportTKGConfigForDockerHandlerFunc turns a function with the right signature into a export t k g config for docker handler
type ExportTKGConfigForDockerHandlerFunc func(ExportTKGConfigForDockerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ExportTKGConfigForDockerHandlerFunc) Handle(params ExportTKGConfigForDockerParams) middleware.Responder {
	return fn(params)
}

// ExportTKGConfigForDockerHandler interface for that can handle valid export t k g config for docker params
type ExportTKGConfigForDockerHandler interface {
	Handle(ExportTKGConfigForDockerParams) middleware.Responder
}

// NewExportTKGConfigForDocker creates a new http.Handler for the export t k g config for docker operation
func NewExportTKGConfigForDocker(ctx *middleware.Context, handler ExportTKGConfigForDockerHandler) *ExportTKGConfigForDocker {
	return &ExportTKGConfigForDocker{Context: ctx, Handler: handler}
}

/*ExportTKGConfigForDocker swagger:route POST /api/provider/docker/config/export docker exportTKGConfigForDocker

Generate TKG configuration file for Docker"

*/
type ExportTKGConfigForDocker struct {
	Context *middleware.Context
	Handler ExportTKGConfigForDockerHandler
}

func (o *ExportTKGConfigForDocker) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewExportTKGConfigForDockerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
