// Code generated by go-swagger; DO NOT EDIT.

package unmanaged

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUnmanagedClusterHandlerFunc turns a function with the right signature into a get unmanaged cluster handler
type GetUnmanagedClusterHandlerFunc func(GetUnmanagedClusterParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUnmanagedClusterHandlerFunc) Handle(params GetUnmanagedClusterParams) middleware.Responder {
	return fn(params)
}

// GetUnmanagedClusterHandler interface for that can handle valid get unmanaged cluster params
type GetUnmanagedClusterHandler interface {
	Handle(GetUnmanagedClusterParams) middleware.Responder
}

// NewGetUnmanagedCluster creates a new http.Handler for the get unmanaged cluster operation
func NewGetUnmanagedCluster(ctx *middleware.Context, handler GetUnmanagedClusterHandler) *GetUnmanagedCluster {
	return &GetUnmanagedCluster{Context: ctx, Handler: handler}
}

/*GetUnmanagedCluster swagger:route GET /api/unmanaged/{clusterName} unmanaged getUnmanagedCluster

Get details of an unmanaged cluster.

*/
type GetUnmanagedCluster struct {
	Context *middleware.Context
	Handler GetUnmanagedClusterHandler
}

func (o *GetUnmanagedCluster) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUnmanagedClusterParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
