// Code generated by go-swagger; DO NOT EDIT.

package unmanaged

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetUnmanagedClustersHandlerFunc turns a function with the right signature into a get unmanaged clusters handler
type GetUnmanagedClustersHandlerFunc func(GetUnmanagedClustersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetUnmanagedClustersHandlerFunc) Handle(params GetUnmanagedClustersParams) middleware.Responder {
	return fn(params)
}

// GetUnmanagedClustersHandler interface for that can handle valid get unmanaged clusters params
type GetUnmanagedClustersHandler interface {
	Handle(GetUnmanagedClustersParams) middleware.Responder
}

// NewGetUnmanagedClusters creates a new http.Handler for the get unmanaged clusters operation
func NewGetUnmanagedClusters(ctx *middleware.Context, handler GetUnmanagedClustersHandler) *GetUnmanagedClusters {
	return &GetUnmanagedClusters{Context: ctx, Handler: handler}
}

/*GetUnmanagedClusters swagger:route GET /api/unmanaged unmanaged getUnmanagedClusters

Retrieve list of unmanaged clusters

*/
type GetUnmanagedClusters struct {
	Context *middleware.Context
	Handler GetUnmanagedClustersHandler
}

func (o *GetUnmanagedClusters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetUnmanagedClustersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
