// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// ApplyTKGConfigForAWSOKCode is the HTTP code returned for type ApplyTKGConfigForAWSOK
const ApplyTKGConfigForAWSOKCode int = 200

/*ApplyTKGConfigForAWSOK Apply change to TKG configuration successfully

swagger:response applyTKGConfigForAWSOK
*/
type ApplyTKGConfigForAWSOK struct {

	/*
	  In: Body
	*/
	Payload *models.ConfigFileInfo `json:"body,omitempty"`
}

// NewApplyTKGConfigForAWSOK creates ApplyTKGConfigForAWSOK with default headers values
func NewApplyTKGConfigForAWSOK() *ApplyTKGConfigForAWSOK {

	return &ApplyTKGConfigForAWSOK{}
}

// WithPayload adds the payload to the apply t k g config for a w s o k response
func (o *ApplyTKGConfigForAWSOK) WithPayload(payload *models.ConfigFileInfo) *ApplyTKGConfigForAWSOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply t k g config for a w s o k response
func (o *ApplyTKGConfigForAWSOK) SetPayload(payload *models.ConfigFileInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyTKGConfigForAWSOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ApplyTKGConfigForAWSBadRequestCode is the HTTP code returned for type ApplyTKGConfigForAWSBadRequest
const ApplyTKGConfigForAWSBadRequestCode int = 400

/*ApplyTKGConfigForAWSBadRequest Bad request

swagger:response applyTKGConfigForAWSBadRequest
*/
type ApplyTKGConfigForAWSBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewApplyTKGConfigForAWSBadRequest creates ApplyTKGConfigForAWSBadRequest with default headers values
func NewApplyTKGConfigForAWSBadRequest() *ApplyTKGConfigForAWSBadRequest {

	return &ApplyTKGConfigForAWSBadRequest{}
}

// WithPayload adds the payload to the apply t k g config for a w s bad request response
func (o *ApplyTKGConfigForAWSBadRequest) WithPayload(payload *models.Error) *ApplyTKGConfigForAWSBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply t k g config for a w s bad request response
func (o *ApplyTKGConfigForAWSBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyTKGConfigForAWSBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ApplyTKGConfigForAWSUnauthorizedCode is the HTTP code returned for type ApplyTKGConfigForAWSUnauthorized
const ApplyTKGConfigForAWSUnauthorizedCode int = 401

/*ApplyTKGConfigForAWSUnauthorized Incorrect credentials

swagger:response applyTKGConfigForAWSUnauthorized
*/
type ApplyTKGConfigForAWSUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewApplyTKGConfigForAWSUnauthorized creates ApplyTKGConfigForAWSUnauthorized with default headers values
func NewApplyTKGConfigForAWSUnauthorized() *ApplyTKGConfigForAWSUnauthorized {

	return &ApplyTKGConfigForAWSUnauthorized{}
}

// WithPayload adds the payload to the apply t k g config for a w s unauthorized response
func (o *ApplyTKGConfigForAWSUnauthorized) WithPayload(payload *models.Error) *ApplyTKGConfigForAWSUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply t k g config for a w s unauthorized response
func (o *ApplyTKGConfigForAWSUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyTKGConfigForAWSUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ApplyTKGConfigForAWSInternalServerErrorCode is the HTTP code returned for type ApplyTKGConfigForAWSInternalServerError
const ApplyTKGConfigForAWSInternalServerErrorCode int = 500

/*ApplyTKGConfigForAWSInternalServerError Internal server error

swagger:response applyTKGConfigForAWSInternalServerError
*/
type ApplyTKGConfigForAWSInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewApplyTKGConfigForAWSInternalServerError creates ApplyTKGConfigForAWSInternalServerError with default headers values
func NewApplyTKGConfigForAWSInternalServerError() *ApplyTKGConfigForAWSInternalServerError {

	return &ApplyTKGConfigForAWSInternalServerError{}
}

// WithPayload adds the payload to the apply t k g config for a w s internal server error response
func (o *ApplyTKGConfigForAWSInternalServerError) WithPayload(payload *models.Error) *ApplyTKGConfigForAWSInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the apply t k g config for a w s internal server error response
func (o *ApplyTKGConfigForAWSInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ApplyTKGConfigForAWSInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
