// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// CreateAWSRegionalClusterOKCode is the HTTP code returned for type CreateAWSRegionalClusterOK
const CreateAWSRegionalClusterOKCode int = 200

/*CreateAWSRegionalClusterOK Creating regional cluster started successfully

swagger:response createAWSRegionalClusterOK
*/
type CreateAWSRegionalClusterOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateAWSRegionalClusterOK creates CreateAWSRegionalClusterOK with default headers values
func NewCreateAWSRegionalClusterOK() *CreateAWSRegionalClusterOK {

	return &CreateAWSRegionalClusterOK{}
}

// WithPayload adds the payload to the create a w s regional cluster o k response
func (o *CreateAWSRegionalClusterOK) WithPayload(payload string) *CreateAWSRegionalClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create a w s regional cluster o k response
func (o *CreateAWSRegionalClusterOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAWSRegionalClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateAWSRegionalClusterBadRequestCode is the HTTP code returned for type CreateAWSRegionalClusterBadRequest
const CreateAWSRegionalClusterBadRequestCode int = 400

/*CreateAWSRegionalClusterBadRequest Bad request

swagger:response createAWSRegionalClusterBadRequest
*/
type CreateAWSRegionalClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAWSRegionalClusterBadRequest creates CreateAWSRegionalClusterBadRequest with default headers values
func NewCreateAWSRegionalClusterBadRequest() *CreateAWSRegionalClusterBadRequest {

	return &CreateAWSRegionalClusterBadRequest{}
}

// WithPayload adds the payload to the create a w s regional cluster bad request response
func (o *CreateAWSRegionalClusterBadRequest) WithPayload(payload *models.Error) *CreateAWSRegionalClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create a w s regional cluster bad request response
func (o *CreateAWSRegionalClusterBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAWSRegionalClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAWSRegionalClusterUnauthorizedCode is the HTTP code returned for type CreateAWSRegionalClusterUnauthorized
const CreateAWSRegionalClusterUnauthorizedCode int = 401

/*CreateAWSRegionalClusterUnauthorized Incorrect credentials

swagger:response createAWSRegionalClusterUnauthorized
*/
type CreateAWSRegionalClusterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAWSRegionalClusterUnauthorized creates CreateAWSRegionalClusterUnauthorized with default headers values
func NewCreateAWSRegionalClusterUnauthorized() *CreateAWSRegionalClusterUnauthorized {

	return &CreateAWSRegionalClusterUnauthorized{}
}

// WithPayload adds the payload to the create a w s regional cluster unauthorized response
func (o *CreateAWSRegionalClusterUnauthorized) WithPayload(payload *models.Error) *CreateAWSRegionalClusterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create a w s regional cluster unauthorized response
func (o *CreateAWSRegionalClusterUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAWSRegionalClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAWSRegionalClusterInternalServerErrorCode is the HTTP code returned for type CreateAWSRegionalClusterInternalServerError
const CreateAWSRegionalClusterInternalServerErrorCode int = 500

/*CreateAWSRegionalClusterInternalServerError Internal server error

swagger:response createAWSRegionalClusterInternalServerError
*/
type CreateAWSRegionalClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAWSRegionalClusterInternalServerError creates CreateAWSRegionalClusterInternalServerError with default headers values
func NewCreateAWSRegionalClusterInternalServerError() *CreateAWSRegionalClusterInternalServerError {

	return &CreateAWSRegionalClusterInternalServerError{}
}

// WithPayload adds the payload to the create a w s regional cluster internal server error response
func (o *CreateAWSRegionalClusterInternalServerError) WithPayload(payload *models.Error) *CreateAWSRegionalClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create a w s regional cluster internal server error response
func (o *CreateAWSRegionalClusterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAWSRegionalClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
