// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAWSNodeTypesParams creates a new GetAWSNodeTypesParams object
//
// There are no default values defined in the spec.
func NewGetAWSNodeTypesParams() GetAWSNodeTypesParams {

	return GetAWSNodeTypesParams{}
}

// GetAWSNodeTypesParams contains all the bound params for the get a w s node types operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAWSNodeTypes
type GetAWSNodeTypesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*AWS availability zone, e.g. us-west-2
	  In: query
	*/
	Az *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAWSNodeTypesParams() beforehand.
func (o *GetAWSNodeTypesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qAz, qhkAz, _ := qs.GetOK("az")
	if err := o.bindAz(qAz, qhkAz, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAz binds and validates parameter Az from query.
func (o *GetAWSNodeTypesParams) bindAz(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Az = &raw

	return nil
}
