// Code generated by go-swagger; DO NOT EDIT.

package aws

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAWSKeyPairsHandlerFunc turns a function with the right signature into a get a w s key pairs handler
type GetAWSKeyPairsHandlerFunc func(GetAWSKeyPairsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAWSKeyPairsHandlerFunc) Handle(params GetAWSKeyPairsParams) middleware.Responder {
	return fn(params)
}

// GetAWSKeyPairsHandler interface for that can handle valid get a w s key pairs params
type GetAWSKeyPairsHandler interface {
	Handle(GetAWSKeyPairsParams) middleware.Responder
}

// NewGetAWSKeyPairs creates a new http.Handler for the get a w s key pairs operation
func NewGetAWSKeyPairs(ctx *middleware.Context, handler GetAWSKeyPairsHandler) *GetAWSKeyPairs {
	return &GetAWSKeyPairs{Context: ctx, Handler: handler}
}

/*GetAWSKeyPairs swagger:route GET /api/provider/aws/keypair aws getAWSKeyPairs

Retrieve AWS key pairs

*/
type GetAWSKeyPairs struct {
	Context *middleware.Context
	Handler GetAWSKeyPairsHandler
}

func (o *GetAWSKeyPairs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAWSKeyPairsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
