export const enum RESOURCE {
    VSPHERE_ADD_RESOURCES = 'VSPHERE_ADD_RESOURCES',
    VSPHERE_DELETE_RESOURCES = 'VSPHERE_DELETE_RESOURCES',
    AWS_ADD_RESOURCES = 'AWS_ADD_RESOURCES',
    AWS_DELETE_RESOURCES = 'AWS_DELETE_RESOURCES',
    AZURE_ADD_RESOURCES = 'AZURE_ADD_RESOURCES',
    AZURE_DELETE_RESOURCES = 'AZURE_DELETE_RESOURCES',
}
