export const VSPHERE_ADD_RESOURCES = 'VSPHERE_ADD_RESOURCES';
export const VSPHERE_DELETE_RESOURCES = 'VSPHERE_DELETE_RESOURCES';
export const AWS_ADD_RESOURCES = 'AWS_ADD_RESOURCES';
export const AWS_DELETE_RESOURCES = 'AWS_DELETE_RESOURCES';
