export const enum RESOURCE {
    ADD_RESOURCES = 'ADD_RESOURCES',
    ADD_RESOURCES_WITH_DEFAULT = 'ADD_RESOURCES_WITH_DEFAULT',
    DELETE_RESOURCES = 'DELETE_RESOURCES',
    DELETE_RESOURCES_WITH_DEFAULT = 'DELETE_RESOURCES_WITH_DEFAULT',
}
