// Code generated by go-swagger; DO NOT EDIT.

package features

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// GetFeatureFlagsOKCode is the HTTP code returned for type GetFeatureFlagsOK
const GetFeatureFlagsOKCode int = 200

/*GetFeatureFlagsOK Successful retrieval of feature flags

swagger:response getFeatureFlagsOK
*/
type GetFeatureFlagsOK struct {

	/*
	  In: Body
	*/
	Payload models.Features `json:"body,omitempty"`
}

// NewGetFeatureFlagsOK creates GetFeatureFlagsOK with default headers values
func NewGetFeatureFlagsOK() *GetFeatureFlagsOK {

	return &GetFeatureFlagsOK{}
}

// WithPayload adds the payload to the get feature flags o k response
func (o *GetFeatureFlagsOK) WithPayload(payload models.Features) *GetFeatureFlagsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get feature flags o k response
func (o *GetFeatureFlagsOK) SetPayload(payload models.Features) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFeatureFlagsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty map
		payload = models.Features{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetFeatureFlagsBadRequestCode is the HTTP code returned for type GetFeatureFlagsBadRequest
const GetFeatureFlagsBadRequestCode int = 400

/*GetFeatureFlagsBadRequest Bad Request

swagger:response getFeatureFlagsBadRequest
*/
type GetFeatureFlagsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFeatureFlagsBadRequest creates GetFeatureFlagsBadRequest with default headers values
func NewGetFeatureFlagsBadRequest() *GetFeatureFlagsBadRequest {

	return &GetFeatureFlagsBadRequest{}
}

// WithPayload adds the payload to the get feature flags bad request response
func (o *GetFeatureFlagsBadRequest) WithPayload(payload *models.Error) *GetFeatureFlagsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get feature flags bad request response
func (o *GetFeatureFlagsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFeatureFlagsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFeatureFlagsUnauthorizedCode is the HTTP code returned for type GetFeatureFlagsUnauthorized
const GetFeatureFlagsUnauthorizedCode int = 401

/*GetFeatureFlagsUnauthorized Incorrect credentials

swagger:response getFeatureFlagsUnauthorized
*/
type GetFeatureFlagsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFeatureFlagsUnauthorized creates GetFeatureFlagsUnauthorized with default headers values
func NewGetFeatureFlagsUnauthorized() *GetFeatureFlagsUnauthorized {

	return &GetFeatureFlagsUnauthorized{}
}

// WithPayload adds the payload to the get feature flags unauthorized response
func (o *GetFeatureFlagsUnauthorized) WithPayload(payload *models.Error) *GetFeatureFlagsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get feature flags unauthorized response
func (o *GetFeatureFlagsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFeatureFlagsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFeatureFlagsInternalServerErrorCode is the HTTP code returned for type GetFeatureFlagsInternalServerError
const GetFeatureFlagsInternalServerErrorCode int = 500

/*GetFeatureFlagsInternalServerError Internal server error

swagger:response getFeatureFlagsInternalServerError
*/
type GetFeatureFlagsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetFeatureFlagsInternalServerError creates GetFeatureFlagsInternalServerError with default headers values
func NewGetFeatureFlagsInternalServerError() *GetFeatureFlagsInternalServerError {

	return &GetFeatureFlagsInternalServerError{}
}

// WithPayload adds the payload to the get feature flags internal server error response
func (o *GetFeatureFlagsInternalServerError) WithPayload(payload *models.Error) *GetFeatureFlagsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get feature flags internal server error response
func (o *GetFeatureFlagsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFeatureFlagsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
