// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Tanzu User Interface API
Tanzu User Interface API.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
