// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AviControllerParams avi controller params
//
// swagger:model AviControllerParams
type AviControllerParams struct {

	// c a data
	CAData string `json:"CAData,omitempty"`

	// host
	Host string `json:"host,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// tenant
	Tenant string `json:"tenant,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this avi controller params
func (m *AviControllerParams) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this avi controller params based on context it is used
func (m *AviControllerParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AviControllerParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AviControllerParams) UnmarshalBinary(b []byte) error {
	var res AviControllerParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
