// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AviConfig avi config
//
// swagger:model AviConfig
type AviConfig struct {

	// ca cert
	CaCert string `json:"ca_cert,omitempty"`

	// cloud
	Cloud string `json:"cloud,omitempty"`

	// control plane ha provider
	ControlPlaneHaProvider bool `json:"controlPlaneHaProvider,omitempty"`

	// controller
	Controller string `json:"controller,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// management cluster vip network cidr
	ManagementClusterVipNetworkCidr string `json:"managementClusterVipNetworkCidr,omitempty"`

	// management cluster vip network name
	ManagementClusterVipNetworkName string `json:"managementClusterVipNetworkName,omitempty"`

	// network
	Network *AviNetworkParams `json:"network,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// service engine
	ServiceEngine string `json:"service_engine,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this avi config
func (m *AviConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNetwork(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AviConfig) validateNetwork(formats strfmt.Registry) error {
	if swag.IsZero(m.Network) { // not required
		return nil
	}

	if m.Network != nil {
		if err := m.Network.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("network")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("network")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this avi config based on the context it is used
func (m *AviConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateNetwork(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AviConfig) contextValidateNetwork(ctx context.Context, formats strfmt.Registry) error {

	if m.Network != nil {
		if err := m.Network.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("network")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("network")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AviConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AviConfig) UnmarshalBinary(b []byte) error {
	var res AviConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
