// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AzureSubnet azure subnet
//
// swagger:model AzureSubnet
type AzureSubnet struct {

	// cidr
	Cidr string `json:"cidr,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this azure subnet
func (m *AzureSubnet) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this azure subnet based on context it is used
func (m *AzureSubnet) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AzureSubnet) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AzureSubnet) UnmarshalBinary(b []byte) error {
	var res AzureSubnet
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
