// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// FeatureMap feature map
// swagger:model FeatureMap
type FeatureMap map[string]string

// Validate validates this feature map
func (m FeatureMap) Validate(formats strfmt.Registry) error {
	return nil
}
