// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// LdapParams ldap params
// swagger:model LdapParams
type LdapParams struct {

	// ldap bind dn
	LdapBindDn string `json:"ldap_bind_dn,omitempty"`

	// ldap bind password
	LdapBindPassword string `json:"ldap_bind_password,omitempty"`

	// ldap group search base dn
	LdapGroupSearchBaseDn string `json:"ldap_group_search_base_dn,omitempty"`

	// ldap group search filter
	LdapGroupSearchFilter string `json:"ldap_group_search_filter,omitempty"`

	// ldap group search group attr
	LdapGroupSearchGroupAttr string `json:"ldap_group_search_group_attr,omitempty"`

	// ldap group search name attr
	LdapGroupSearchNameAttr string `json:"ldap_group_search_name_attr,omitempty"`

	// ldap group search user attr
	LdapGroupSearchUserAttr string `json:"ldap_group_search_user_attr,omitempty"`

	// ldap root ca
	LdapRootCa string `json:"ldap_root_ca,omitempty"`

	// ldap test group
	LdapTestGroup string `json:"ldap_test_group,omitempty"`

	// ldap test user
	LdapTestUser string `json:"ldap_test_user,omitempty"`

	// ldap url
	LdapURL string `json:"ldap_url,omitempty"`

	// ldap user search base dn
	LdapUserSearchBaseDn string `json:"ldap_user_search_base_dn,omitempty"`

	// ldap user search email attr
	LdapUserSearchEmailAttr string `json:"ldap_user_search_email_attr,omitempty"`

	// ldap user search filter
	LdapUserSearchFilter string `json:"ldap_user_search_filter,omitempty"`

	// ldap user search id attr
	LdapUserSearchIDAttr string `json:"ldap_user_search_id_attr,omitempty"`

	// ldap user search name attr
	LdapUserSearchNameAttr string `json:"ldap_user_search_name_attr,omitempty"`

	// ldap user search username
	LdapUserSearchUsername string `json:"ldap_user_search_username,omitempty"`
}

func (m *LdapParams) UnmarshalJSON(b []byte) error {
	type LdapParamsAlias LdapParams
	var t LdapParamsAlias
	if err := json.Unmarshal([]byte("{\"ldap_group_search_name_attr\":\"cn\",\"ldap_group_search_user_attr\":\"DN\",\"ldap_user_search_email_attr\":\"userPrincipalName\",\"ldap_user_search_id_attr\":\"DN\",\"ldap_user_search_username\":\"userPrincipalName\"}"), &t); err != nil {
		return err
	}
	if err := json.Unmarshal(b, &t); err != nil {
		return err
	}
	*m = LdapParams(t)
	return nil
}

// Validate validates this ldap params
func (m *LdapParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LdapParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LdapParams) UnmarshalBinary(b []byte) error {
	var res LdapParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
