// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProviderInfo provider info
//
// swagger:model providerInfo
type ProviderInfo struct {

	// provider
	Provider string `json:"provider,omitempty"`

	// tkr version
	TkrVersion string `json:"tkrVersion,omitempty"`
}

// Validate validates this provider info
func (m *ProviderInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this provider info based on context it is used
func (m *ProviderInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProviderInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProviderInfo) UnmarshalBinary(b []byte) error {
	var res ProviderInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
