// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VSphereCredentials v sphere credentials
//
// swagger:model VSphereCredentials
type VSphereCredentials struct {

	// host
	Host string `json:"host,omitempty"`

	// insecure
	Insecure *bool `json:"insecure,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// thumbprint
	Thumbprint string `json:"thumbprint,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this v sphere credentials
func (m *VSphereCredentials) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v sphere credentials based on context it is used
func (m *VSphereCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VSphereCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VSphereCredentials) UnmarshalBinary(b []byte) error {
	var res VSphereCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
