#syntax=docker/dockerfile:1.4

# Copyright 2022 VMware, Inc.
# SPDX-License-Identifier: Apache-2.0

FROM bitnami/golang:1.18.0

ARG TARGETARCH

WORKDIR /app

ARG TCE_VERSION=v0.12.0-rc.2

RUN curl --fail --silent -L -o /tmp/src.tar.gz https://github.com/vmware-tanzu/community-edition/archive/refs/tags/${TCE_VERSION}.tar.gz && \
    tar --strip-components 1 -xvf /tmp/src.tar.gz

WORKDIR /app/cli/cmd/plugin/unmanaged-cluster

RUN go mod download

RUN GOARCH=${TARGETARCH} go build -o /tanzu-unmanaged-cluster-${TARGETARCH}
