// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// CreateAzureRegionalClusterOKCode is the HTTP code returned for type CreateAzureRegionalClusterOK
const CreateAzureRegionalClusterOKCode int = 200

/*CreateAzureRegionalClusterOK Creating regional cluster started successfully

swagger:response createAzureRegionalClusterOK
*/
type CreateAzureRegionalClusterOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCreateAzureRegionalClusterOK creates CreateAzureRegionalClusterOK with default headers values
func NewCreateAzureRegionalClusterOK() *CreateAzureRegionalClusterOK {

	return &CreateAzureRegionalClusterOK{}
}

// WithPayload adds the payload to the create azure regional cluster o k response
func (o *CreateAzureRegionalClusterOK) WithPayload(payload string) *CreateAzureRegionalClusterOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create azure regional cluster o k response
func (o *CreateAzureRegionalClusterOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAzureRegionalClusterOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// CreateAzureRegionalClusterBadRequestCode is the HTTP code returned for type CreateAzureRegionalClusterBadRequest
const CreateAzureRegionalClusterBadRequestCode int = 400

/*CreateAzureRegionalClusterBadRequest Bad request

swagger:response createAzureRegionalClusterBadRequest
*/
type CreateAzureRegionalClusterBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAzureRegionalClusterBadRequest creates CreateAzureRegionalClusterBadRequest with default headers values
func NewCreateAzureRegionalClusterBadRequest() *CreateAzureRegionalClusterBadRequest {

	return &CreateAzureRegionalClusterBadRequest{}
}

// WithPayload adds the payload to the create azure regional cluster bad request response
func (o *CreateAzureRegionalClusterBadRequest) WithPayload(payload *models.Error) *CreateAzureRegionalClusterBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create azure regional cluster bad request response
func (o *CreateAzureRegionalClusterBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAzureRegionalClusterBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAzureRegionalClusterUnauthorizedCode is the HTTP code returned for type CreateAzureRegionalClusterUnauthorized
const CreateAzureRegionalClusterUnauthorizedCode int = 401

/*CreateAzureRegionalClusterUnauthorized Incorrect credentials

swagger:response createAzureRegionalClusterUnauthorized
*/
type CreateAzureRegionalClusterUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAzureRegionalClusterUnauthorized creates CreateAzureRegionalClusterUnauthorized with default headers values
func NewCreateAzureRegionalClusterUnauthorized() *CreateAzureRegionalClusterUnauthorized {

	return &CreateAzureRegionalClusterUnauthorized{}
}

// WithPayload adds the payload to the create azure regional cluster unauthorized response
func (o *CreateAzureRegionalClusterUnauthorized) WithPayload(payload *models.Error) *CreateAzureRegionalClusterUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create azure regional cluster unauthorized response
func (o *CreateAzureRegionalClusterUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAzureRegionalClusterUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateAzureRegionalClusterInternalServerErrorCode is the HTTP code returned for type CreateAzureRegionalClusterInternalServerError
const CreateAzureRegionalClusterInternalServerErrorCode int = 500

/*CreateAzureRegionalClusterInternalServerError Internal server error

swagger:response createAzureRegionalClusterInternalServerError
*/
type CreateAzureRegionalClusterInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCreateAzureRegionalClusterInternalServerError creates CreateAzureRegionalClusterInternalServerError with default headers values
func NewCreateAzureRegionalClusterInternalServerError() *CreateAzureRegionalClusterInternalServerError {

	return &CreateAzureRegionalClusterInternalServerError{}
}

// WithPayload adds the payload to the create azure regional cluster internal server error response
func (o *CreateAzureRegionalClusterInternalServerError) WithPayload(payload *models.Error) *CreateAzureRegionalClusterInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create azure regional cluster internal server error response
func (o *CreateAzureRegionalClusterInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateAzureRegionalClusterInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
