// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAzureResourceGroupsParams creates a new GetAzureResourceGroupsParams object
// no default values defined in spec.
func NewGetAzureResourceGroupsParams() GetAzureResourceGroupsParams {

	return GetAzureResourceGroupsParams{}
}

// GetAzureResourceGroupsParams contains all the bound params for the get azure resource groups operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAzureResourceGroups
type GetAzureResourceGroupsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Azure region
	  Required: true
	  In: query
	*/
	Location string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAzureResourceGroupsParams() beforehand.
func (o *GetAzureResourceGroupsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLocation, qhkLocation, _ := qs.GetOK("location")
	if err := o.bindLocation(qLocation, qhkLocation, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindLocation binds and validates parameter Location from query.
func (o *GetAzureResourceGroupsParams) bindLocation(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("location", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("location", "query", raw); err != nil {
		return err
	}

	o.Location = raw

	return nil
}
