// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// GetAzureRegionsOKCode is the HTTP code returned for type GetAzureRegionsOK
const GetAzureRegionsOKCode int = 200

/*GetAzureRegionsOK Successful retrieval of Azure regions

swagger:response getAzureRegionsOK
*/
type GetAzureRegionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.AzureLocation `json:"body,omitempty"`
}

// NewGetAzureRegionsOK creates GetAzureRegionsOK with default headers values
func NewGetAzureRegionsOK() *GetAzureRegionsOK {

	return &GetAzureRegionsOK{}
}

// WithPayload adds the payload to the get azure regions o k response
func (o *GetAzureRegionsOK) WithPayload(payload []*models.AzureLocation) *GetAzureRegionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get azure regions o k response
func (o *GetAzureRegionsOK) SetPayload(payload []*models.AzureLocation) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAzureRegionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.AzureLocation, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAzureRegionsBadRequestCode is the HTTP code returned for type GetAzureRegionsBadRequest
const GetAzureRegionsBadRequestCode int = 400

/*GetAzureRegionsBadRequest Bad Request

swagger:response getAzureRegionsBadRequest
*/
type GetAzureRegionsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAzureRegionsBadRequest creates GetAzureRegionsBadRequest with default headers values
func NewGetAzureRegionsBadRequest() *GetAzureRegionsBadRequest {

	return &GetAzureRegionsBadRequest{}
}

// WithPayload adds the payload to the get azure regions bad request response
func (o *GetAzureRegionsBadRequest) WithPayload(payload *models.Error) *GetAzureRegionsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get azure regions bad request response
func (o *GetAzureRegionsBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAzureRegionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAzureRegionsUnauthorizedCode is the HTTP code returned for type GetAzureRegionsUnauthorized
const GetAzureRegionsUnauthorizedCode int = 401

/*GetAzureRegionsUnauthorized Incorrect credentials

swagger:response getAzureRegionsUnauthorized
*/
type GetAzureRegionsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAzureRegionsUnauthorized creates GetAzureRegionsUnauthorized with default headers values
func NewGetAzureRegionsUnauthorized() *GetAzureRegionsUnauthorized {

	return &GetAzureRegionsUnauthorized{}
}

// WithPayload adds the payload to the get azure regions unauthorized response
func (o *GetAzureRegionsUnauthorized) WithPayload(payload *models.Error) *GetAzureRegionsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get azure regions unauthorized response
func (o *GetAzureRegionsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAzureRegionsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAzureRegionsInternalServerErrorCode is the HTTP code returned for type GetAzureRegionsInternalServerError
const GetAzureRegionsInternalServerErrorCode int = 500

/*GetAzureRegionsInternalServerError Internal server error

swagger:response getAzureRegionsInternalServerError
*/
type GetAzureRegionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAzureRegionsInternalServerError creates GetAzureRegionsInternalServerError with default headers values
func NewGetAzureRegionsInternalServerError() *GetAzureRegionsInternalServerError {

	return &GetAzureRegionsInternalServerError{}
}

// WithPayload adds the payload to the get azure regions internal server error response
func (o *GetAzureRegionsInternalServerError) WithPayload(payload *models.Error) *GetAzureRegionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get azure regions internal server error response
func (o *GetAzureRegionsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAzureRegionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
