// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ImportTKGConfigForAzureHandlerFunc turns a function with the right signature into a import t k g config for azure handler
type ImportTKGConfigForAzureHandlerFunc func(ImportTKGConfigForAzureParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ImportTKGConfigForAzureHandlerFunc) Handle(params ImportTKGConfigForAzureParams) middleware.Responder {
	return fn(params)
}

// ImportTKGConfigForAzureHandler interface for that can handle valid import t k g config for azure params
type ImportTKGConfigForAzureHandler interface {
	Handle(ImportTKGConfigForAzureParams) middleware.Responder
}

// NewImportTKGConfigForAzure creates a new http.Handler for the import t k g config for azure operation
func NewImportTKGConfigForAzure(ctx *middleware.Context, handler ImportTKGConfigForAzureHandler) *ImportTKGConfigForAzure {
	return &ImportTKGConfigForAzure{Context: ctx, Handler: handler}
}

/*ImportTKGConfigForAzure swagger:route POST /api/provider/azure/config/import azure importTKGConfigForAzure

Generate TKG configuration object for azure

*/
type ImportTKGConfigForAzure struct {
	Context *middleware.Context
	Handler ImportTKGConfigForAzureHandler
}

func (o *ImportTKGConfigForAzure) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewImportTKGConfigForAzureParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
