// Code generated by go-swagger; DO NOT EDIT.

package azure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// SetAzureEndpointCreatedCode is the HTTP code returned for type SetAzureEndpointCreated
const SetAzureEndpointCreatedCode int = 201

/*SetAzureEndpointCreated Connection successful

swagger:response setAzureEndpointCreated
*/
type SetAzureEndpointCreated struct {
}

// NewSetAzureEndpointCreated creates SetAzureEndpointCreated with default headers values
func NewSetAzureEndpointCreated() *SetAzureEndpointCreated {

	return &SetAzureEndpointCreated{}
}

// WriteResponse to the client
func (o *SetAzureEndpointCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// SetAzureEndpointBadRequestCode is the HTTP code returned for type SetAzureEndpointBadRequest
const SetAzureEndpointBadRequestCode int = 400

/*SetAzureEndpointBadRequest Bad request

swagger:response setAzureEndpointBadRequest
*/
type SetAzureEndpointBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetAzureEndpointBadRequest creates SetAzureEndpointBadRequest with default headers values
func NewSetAzureEndpointBadRequest() *SetAzureEndpointBadRequest {

	return &SetAzureEndpointBadRequest{}
}

// WithPayload adds the payload to the set azure endpoint bad request response
func (o *SetAzureEndpointBadRequest) WithPayload(payload *models.Error) *SetAzureEndpointBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set azure endpoint bad request response
func (o *SetAzureEndpointBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetAzureEndpointBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SetAzureEndpointUnauthorizedCode is the HTTP code returned for type SetAzureEndpointUnauthorized
const SetAzureEndpointUnauthorizedCode int = 401

/*SetAzureEndpointUnauthorized Incorrect credentials

swagger:response setAzureEndpointUnauthorized
*/
type SetAzureEndpointUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetAzureEndpointUnauthorized creates SetAzureEndpointUnauthorized with default headers values
func NewSetAzureEndpointUnauthorized() *SetAzureEndpointUnauthorized {

	return &SetAzureEndpointUnauthorized{}
}

// WithPayload adds the payload to the set azure endpoint unauthorized response
func (o *SetAzureEndpointUnauthorized) WithPayload(payload *models.Error) *SetAzureEndpointUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set azure endpoint unauthorized response
func (o *SetAzureEndpointUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetAzureEndpointUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SetAzureEndpointInternalServerErrorCode is the HTTP code returned for type SetAzureEndpointInternalServerError
const SetAzureEndpointInternalServerErrorCode int = 500

/*SetAzureEndpointInternalServerError Internal server error

swagger:response setAzureEndpointInternalServerError
*/
type SetAzureEndpointInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSetAzureEndpointInternalServerError creates SetAzureEndpointInternalServerError with default headers values
func NewSetAzureEndpointInternalServerError() *SetAzureEndpointInternalServerError {

	return &SetAzureEndpointInternalServerError{}
}

// WithPayload adds the payload to the set azure endpoint internal server error response
func (o *SetAzureEndpointInternalServerError) WithPayload(payload *models.Error) *SetAzureEndpointInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the set azure endpoint internal server error response
func (o *SetAzureEndpointInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SetAzureEndpointInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
