// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetMgmtClustersHandlerFunc turns a function with the right signature into a get mgmt clusters handler
type GetMgmtClustersHandlerFunc func(GetMgmtClustersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMgmtClustersHandlerFunc) Handle(params GetMgmtClustersParams) middleware.Responder {
	return fn(params)
}

// GetMgmtClustersHandler interface for that can handle valid get mgmt clusters params
type GetMgmtClustersHandler interface {
	Handle(GetMgmtClustersParams) middleware.Responder
}

// NewGetMgmtClusters creates a new http.Handler for the get mgmt clusters operation
func NewGetMgmtClusters(ctx *middleware.Context, handler GetMgmtClustersHandler) *GetMgmtClusters {
	return &GetMgmtClusters{Context: ctx, Handler: handler}
}

/*GetMgmtClusters swagger:route GET /api/management management getMgmtClusters

Retrieve list of management clusters

*/
type GetMgmtClusters struct {
	Context *middleware.Context
	Handler GetMgmtClustersHandler
}

func (o *GetMgmtClusters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMgmtClustersParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
