// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterClassesParams creates a new GetClusterClassesParams object
// no default values defined in spec.
func NewGetClusterClassesParams() GetClusterClassesParams {

	return GetClusterClassesParams{}
}

// GetClusterClassesParams contains all the bound params for the get cluster classes operation
// typically these are obtained from a http.Request
//
// swagger:parameters getClusterClasses
type GetClusterClassesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The name of the management cluster.
	  Required: true
	  In: path
	*/
	ManagementClusterName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClusterClassesParams() beforehand.
func (o *GetClusterClassesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rManagementClusterName, rhkManagementClusterName, _ := route.Params.GetOK("managementClusterName")
	if err := o.bindManagementClusterName(rManagementClusterName, rhkManagementClusterName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindManagementClusterName binds and validates parameter ManagementClusterName from path.
func (o *GetClusterClassesParams) bindManagementClusterName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ManagementClusterName = raw

	return nil
}
