// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// GetClusterClassOKCode is the HTTP code returned for type GetClusterClassOK
const GetClusterClassOKCode int = 200

/*GetClusterClassOK Retrieve list of management cluster ClusterClasses.

swagger:response getClusterClassOK
*/
type GetClusterClassOK struct {

	/*A list of ClusterClasses.
	  In: Body
	*/
	Payload []*models.ClusterClass `json:"body,omitempty"`
}

// NewGetClusterClassOK creates GetClusterClassOK with default headers values
func NewGetClusterClassOK() *GetClusterClassOK {

	return &GetClusterClassOK{}
}

// WithPayload adds the payload to the get cluster class o k response
func (o *GetClusterClassOK) WithPayload(payload []*models.ClusterClass) *GetClusterClassOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster class o k response
func (o *GetClusterClassOK) SetPayload(payload []*models.ClusterClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ClusterClass, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetClusterClassBadRequestCode is the HTTP code returned for type GetClusterClassBadRequest
const GetClusterClassBadRequestCode int = 400

/*GetClusterClassBadRequest Bad request

swagger:response getClusterClassBadRequest
*/
type GetClusterClassBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassBadRequest creates GetClusterClassBadRequest with default headers values
func NewGetClusterClassBadRequest() *GetClusterClassBadRequest {

	return &GetClusterClassBadRequest{}
}

// WithPayload adds the payload to the get cluster class bad request response
func (o *GetClusterClassBadRequest) WithPayload(payload *models.Error) *GetClusterClassBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster class bad request response
func (o *GetClusterClassBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClusterClassUnauthorizedCode is the HTTP code returned for type GetClusterClassUnauthorized
const GetClusterClassUnauthorizedCode int = 401

/*GetClusterClassUnauthorized Incorrect credentials

swagger:response getClusterClassUnauthorized
*/
type GetClusterClassUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassUnauthorized creates GetClusterClassUnauthorized with default headers values
func NewGetClusterClassUnauthorized() *GetClusterClassUnauthorized {

	return &GetClusterClassUnauthorized{}
}

// WithPayload adds the payload to the get cluster class unauthorized response
func (o *GetClusterClassUnauthorized) WithPayload(payload *models.Error) *GetClusterClassUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster class unauthorized response
func (o *GetClusterClassUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClusterClassInternalServerErrorCode is the HTTP code returned for type GetClusterClassInternalServerError
const GetClusterClassInternalServerErrorCode int = 500

/*GetClusterClassInternalServerError Internal server error

swagger:response getClusterClassInternalServerError
*/
type GetClusterClassInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassInternalServerError creates GetClusterClassInternalServerError with default headers values
func NewGetClusterClassInternalServerError() *GetClusterClassInternalServerError {

	return &GetClusterClassInternalServerError{}
}

// WithPayload adds the payload to the get cluster class internal server error response
func (o *GetClusterClassInternalServerError) WithPayload(payload *models.Error) *GetClusterClassInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster class internal server error response
func (o *GetClusterClassInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
