// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// GetMgmtClustersOKCode is the HTTP code returned for type GetMgmtClustersOK
const GetMgmtClustersOKCode int = 200

/*GetMgmtClustersOK Retrieve list of management clusters

swagger:response getMgmtClustersOK
*/
type GetMgmtClustersOK struct {

	/*a list of management clusters
	  In: Body
	*/
	Payload []*models.ManagementCluster `json:"body,omitempty"`
}

// NewGetMgmtClustersOK creates GetMgmtClustersOK with default headers values
func NewGetMgmtClustersOK() *GetMgmtClustersOK {

	return &GetMgmtClustersOK{}
}

// WithPayload adds the payload to the get mgmt clusters o k response
func (o *GetMgmtClustersOK) WithPayload(payload []*models.ManagementCluster) *GetMgmtClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mgmt clusters o k response
func (o *GetMgmtClustersOK) SetPayload(payload []*models.ManagementCluster) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMgmtClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ManagementCluster, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetMgmtClustersBadRequestCode is the HTTP code returned for type GetMgmtClustersBadRequest
const GetMgmtClustersBadRequestCode int = 400

/*GetMgmtClustersBadRequest Bad request

swagger:response getMgmtClustersBadRequest
*/
type GetMgmtClustersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMgmtClustersBadRequest creates GetMgmtClustersBadRequest with default headers values
func NewGetMgmtClustersBadRequest() *GetMgmtClustersBadRequest {

	return &GetMgmtClustersBadRequest{}
}

// WithPayload adds the payload to the get mgmt clusters bad request response
func (o *GetMgmtClustersBadRequest) WithPayload(payload *models.Error) *GetMgmtClustersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mgmt clusters bad request response
func (o *GetMgmtClustersBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMgmtClustersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMgmtClustersUnauthorizedCode is the HTTP code returned for type GetMgmtClustersUnauthorized
const GetMgmtClustersUnauthorizedCode int = 401

/*GetMgmtClustersUnauthorized Incorrect credentials

swagger:response getMgmtClustersUnauthorized
*/
type GetMgmtClustersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMgmtClustersUnauthorized creates GetMgmtClustersUnauthorized with default headers values
func NewGetMgmtClustersUnauthorized() *GetMgmtClustersUnauthorized {

	return &GetMgmtClustersUnauthorized{}
}

// WithPayload adds the payload to the get mgmt clusters unauthorized response
func (o *GetMgmtClustersUnauthorized) WithPayload(payload *models.Error) *GetMgmtClustersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mgmt clusters unauthorized response
func (o *GetMgmtClustersUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMgmtClustersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetMgmtClustersInternalServerErrorCode is the HTTP code returned for type GetMgmtClustersInternalServerError
const GetMgmtClustersInternalServerErrorCode int = 500

/*GetMgmtClustersInternalServerError Internal server error

swagger:response getMgmtClustersInternalServerError
*/
type GetMgmtClustersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMgmtClustersInternalServerError creates GetMgmtClustersInternalServerError with default headers values
func NewGetMgmtClustersInternalServerError() *GetMgmtClustersInternalServerError {

	return &GetMgmtClustersInternalServerError{}
}

// WithPayload adds the payload to the get mgmt clusters internal server error response
func (o *GetMgmtClustersInternalServerError) WithPayload(payload *models.Error) *GetMgmtClustersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get mgmt clusters internal server error response
func (o *GetMgmtClustersInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMgmtClustersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
