// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetClusterClassParams creates a new GetClusterClassParams object
// no default values defined in spec.
func NewGetClusterClassParams() GetClusterClassParams {

	return GetClusterClassParams{}
}

// GetClusterClassParams contains all the bound params for the get cluster class operation
// typically these are obtained from a http.Request
//
// swagger:parameters getClusterClass
type GetClusterClassParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The ClusterClass identifier.
	  Required: true
	  In: path
	*/
	ClusterClassName string
	/*The name of the management cluster.
	  Required: true
	  In: path
	*/
	ManagementClusterName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetClusterClassParams() beforehand.
func (o *GetClusterClassParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rClusterClassName, rhkClusterClassName, _ := route.Params.GetOK("clusterClassName")
	if err := o.bindClusterClassName(rClusterClassName, rhkClusterClassName, route.Formats); err != nil {
		res = append(res, err)
	}

	rManagementClusterName, rhkManagementClusterName, _ := route.Params.GetOK("managementClusterName")
	if err := o.bindManagementClusterName(rManagementClusterName, rhkManagementClusterName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindClusterClassName binds and validates parameter ClusterClassName from path.
func (o *GetClusterClassParams) bindClusterClassName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ClusterClassName = raw

	return nil
}

// bindManagementClusterName binds and validates parameter ManagementClusterName from path.
func (o *GetClusterClassParams) bindManagementClusterName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ManagementClusterName = raw

	return nil
}
