// Code generated by go-swagger; DO NOT EDIT.

package management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/vmware-tanzu/community-edition/cli/cmd/plugin/ui/server/models"
)

// GetClusterClassesOKCode is the HTTP code returned for type GetClusterClassesOK
const GetClusterClassesOKCode int = 200

/*GetClusterClassesOK Retrieve list of management cluster ClusterClasses.

swagger:response getClusterClassesOK
*/
type GetClusterClassesOK struct {

	/*A list of ClusterClasses.
	  In: Body
	*/
	Payload []*models.ClusterClass `json:"body,omitempty"`
}

// NewGetClusterClassesOK creates GetClusterClassesOK with default headers values
func NewGetClusterClassesOK() *GetClusterClassesOK {

	return &GetClusterClassesOK{}
}

// WithPayload adds the payload to the get cluster classes o k response
func (o *GetClusterClassesOK) WithPayload(payload []*models.ClusterClass) *GetClusterClassesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster classes o k response
func (o *GetClusterClassesOK) SetPayload(payload []*models.ClusterClass) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ClusterClass, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetClusterClassesBadRequestCode is the HTTP code returned for type GetClusterClassesBadRequest
const GetClusterClassesBadRequestCode int = 400

/*GetClusterClassesBadRequest Bad request

swagger:response getClusterClassesBadRequest
*/
type GetClusterClassesBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassesBadRequest creates GetClusterClassesBadRequest with default headers values
func NewGetClusterClassesBadRequest() *GetClusterClassesBadRequest {

	return &GetClusterClassesBadRequest{}
}

// WithPayload adds the payload to the get cluster classes bad request response
func (o *GetClusterClassesBadRequest) WithPayload(payload *models.Error) *GetClusterClassesBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster classes bad request response
func (o *GetClusterClassesBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassesBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClusterClassesUnauthorizedCode is the HTTP code returned for type GetClusterClassesUnauthorized
const GetClusterClassesUnauthorizedCode int = 401

/*GetClusterClassesUnauthorized Incorrect credentials

swagger:response getClusterClassesUnauthorized
*/
type GetClusterClassesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassesUnauthorized creates GetClusterClassesUnauthorized with default headers values
func NewGetClusterClassesUnauthorized() *GetClusterClassesUnauthorized {

	return &GetClusterClassesUnauthorized{}
}

// WithPayload adds the payload to the get cluster classes unauthorized response
func (o *GetClusterClassesUnauthorized) WithPayload(payload *models.Error) *GetClusterClassesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster classes unauthorized response
func (o *GetClusterClassesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClusterClassesInternalServerErrorCode is the HTTP code returned for type GetClusterClassesInternalServerError
const GetClusterClassesInternalServerErrorCode int = 500

/*GetClusterClassesInternalServerError Internal server error

swagger:response getClusterClassesInternalServerError
*/
type GetClusterClassesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetClusterClassesInternalServerError creates GetClusterClassesInternalServerError with default headers values
func NewGetClusterClassesInternalServerError() *GetClusterClassesInternalServerError {

	return &GetClusterClassesInternalServerError{}
}

// WithPayload adds the payload to the get cluster classes internal server error response
func (o *GetClusterClassesInternalServerError) WithPayload(payload *models.Error) *GetClusterClassesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get cluster classes internal server error response
func (o *GetClusterClassesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClusterClassesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
