import {
    AZURE_FIELDS,
    AZURE_NODE_PROFILE_NAMES,
} from '../../../views/management-cluster/azure/azure-mc-basic/AzureManagementClusterBasic.constants';
import { KeyOfStringToArray } from '../../types/types';

export const AZURE_DEFAULT_VALUES = {
    [AZURE_FIELDS.NODE_PROFILE]: AZURE_NODE_PROFILE_NAMES.SINGLE_NODE,
    [AZURE_FIELDS.CEIP_OPT_IN]: false,
    [AZURE_FIELDS.CONTROL_PLANE_FLAVOR]: 'dev',
    [AZURE_FIELDS.PRIVATE_AZURE_CLUSTER]: false,
    [AZURE_FIELDS.ACTIVATE_AUDIT_LOGGING]: false,
    [AZURE_FIELDS.MACHINE_HEALTH_CHECK_ENABLED]: true,
    [AZURE_FIELDS.RESOURCE_GROUP]: 'tanzu-resource-group-default',
    // VNET
    [AZURE_FIELDS.VNET_NAME]: 'tanzu-vnet-name-default',
    [AZURE_FIELDS.VNET_CIDR]: '10.0.0.0/16',
    [AZURE_FIELDS.CONTROL_PLANE_SUBNET]: 'tanzu-control-plane-subnet-default',
    [AZURE_FIELDS.CONTROL_PLANE_SUBNET_CIDR]: '10.0.0.0/24',
    [AZURE_FIELDS.WORKER_NODE_SUBNET]: 'tanzu-worker-node-subnet-default',
    [AZURE_FIELDS.WORKER_NODE_SUBNET_CIDR]: '10.0.1.0/24',
    // Network
    [AZURE_FIELDS.CNI_TYPE]: 'antrea', // TODO: refactor to use CniProviders Const
    [AZURE_FIELDS.CLUSTER_POD_CIDR]: '100.96.0.0/11',
    [AZURE_FIELDS.CLUSTER_SERVICE_CIDR]: '100.64.0.0/13',
    [AZURE_FIELDS.ACTIVATE_PROXY_SETTINGS]: false,
};
const PREFERRED_SINGLE_NODE_INSTANCE_TYPES_ORDERED: Array<string> = [
    'Standard_D2s_v3',
    'Standard_D4s_v3',
    'Standard_D2_v3',
    'Standard_D4_v3',
    'Standard_A2_v2',
    'Standard_A1_v2',
    'Standard_A4_v2',
    'Standard_B2ms',
    'Standard_B2s',
    'Standard_B4ms',
    'Standard_DC2s_v2',
    'Standard_DC1s_v2',
    'Standard_DC4s_v2',
    'Standard_DC2s_v3',
    'Standard_DC1s_v3',
    'Standard_DC4s_v3',
    'Standard_DC2ds_v3',
    'Standard_DC1ds_v3',
    'Standard_DC4ds_v3',
    'Standard_D2_v2',
    'Standard_D1_v2',
    'Standard_D3_v2',
    'Standard_D2_v4',
    'Standard_D4_v4',
    'Standard_D2s_v4',
    'Standard_D4s_v4',
    'Standard_D2a_v4',
    'Standard_D4a_v4',
    'Standard_D2as_v4',
    'Standard_D4as_v4',
    'Standard_D2d_v4',
    'Standard_D4d_v4',
    'Standard_D2ds_v4',
    'Standard_D4ds_v4',
    'Standard_D2_v5',
    'Standard_D4_v5',
    'Standard_D2s_v5',
    'Standard_D4s_v5',
    'Standard_D2d_v5',
    'Standard_D4d_v5',
    'Standard_D2ds_v5',
    'Standard_D4ds_v5',
    'Standard_D2as_v5',
    'Standard_D4as_v5',
    'Standard_D2ads_v5',
    'Standard_D4ads_v5',
    'Standard_DC2as_v5',
    'Standard_DC4as_v5',
    'Standard_DC2ads_v5',
    'Standard_DC4ads_v5',
];

const PREFERRED_PRODUCTION_READY_INSTANCE_TYPES_ORDERED: Array<string> = [
    'Standard_D4s_v3',
    'Standard_D2s_v3',
    'Standard_D8s_v3',
    'Standard_D4_v3',
    'Standard_D2_v3',
    'Standard_D8_v3',
    'Standard_A4_v2',
    'Standard_A2_v2',
    'Standard_A8_v2',
    'Standard_B4ms',
    'Standard_B2ms',
    'Standard_B8ms',
    'Standard_DC4s_v2',
    'Standard_DC2s_v2',
    'Standard_DC8_v2',
    'Standard_DC4s_v3',
    'Standard_DC2s_v3',
    'Standard_DC8s_v3',
    'Standard_DC4ds_v3',
    'Standard_DC2ds_v3',
    'Standard_DC8ds_v3',
    'Standard_D4_v2',
    'Standard_D3_v2',
    'Standard_D5_v2',
    'Standard_DS4_v2',
    'Standard_DS3_v2',
    'Standard_DS5_v2',
    'Standard_D4_v4',
    'Standard_D2_v4',
    'Standard_D8_v4',
    'Standard_D4s_v4',
    'Standard_D2s_v4',
    'Standard_D8s_v4',
    'Standard_D4a_v4',
    'Standard_D2a_v4',
    'Standard_D8a_v4',
    'Standard_D4as_v4',
    'Standard_D2as_v4',
    'Standard_D8as_v4',
    'Standard_D4d_v4',
    'Standard_D2d_v4',
    'Standard_D8d_v4',
    'Standard_D4ds_v4',
    'Standard_D2ds_v4',
    'Standard_D8ds_v4',
    'Standard_D4_v5',
    'Standard_D2_v5',
    'Standard_D8_v5',
    'Standard_D4s_v5',
    'Standard_D2s_v5',
    'Standard_D8s_v5',
    'Standard_D4d_v5',
    'Standard_D2d_v5',
    'Standard_D8d_v5',
    'Standard_D4as_v5',
    'Standard_D2as_v5',
    'Standard_D8as_v5',
    'Standard_D4ads_v5',
    'Standard_D2ads_v5',
    'Standard_D8ads_v5',
    'Standard_DC4as_v5',
    'Standard_DC2as_v5',
    'Standard_DC8as_v5',
    'Standard_DC4ads_v5',
    'Standard_DC2ads_v5',
    'Standard_DC8ads_v5',
];

const AZURE_DEFAULT_INSTANCE_TYPES: KeyOfStringToArray = {
    [AZURE_NODE_PROFILE_NAMES.SINGLE_NODE]: PREFERRED_SINGLE_NODE_INSTANCE_TYPES_ORDERED,
    [AZURE_NODE_PROFILE_NAMES.HIGH_AVAILABILITY]: PREFERRED_SINGLE_NODE_INSTANCE_TYPES_ORDERED,
    [AZURE_NODE_PROFILE_NAMES.PRODUCTION_READY]: PREFERRED_PRODUCTION_READY_INSTANCE_TYPES_ORDERED,
};

/**
 * @method retrieveAzureInstanceType
 * @param nodeProfile - node profile name set by ManagementClusterSettings.tsx; references key of AZURE_DEFAULT_INSTANCE_TYPES
 * defaults const.
 * Returns aws instance type string corresponding to selected node profile.
 */
export function getNodeTypesByNodeProfile(nodeProfile: string): Array<string> {
    if (nodeProfile && AZURE_DEFAULT_INSTANCE_TYPES[nodeProfile]) {
        return AZURE_DEFAULT_INSTANCE_TYPES[nodeProfile];
    } else {
        console.warn(`provided node profile value not found in AZURE_DEFAULT_INSTANCE_TYPES: ${nodeProfile}`);
        return AZURE_DEFAULT_INSTANCE_TYPES[AZURE_NODE_PROFILE_NAMES.SINGLE_NODE];
    }
}
