// Code generated by go-swagger; DO NOT EDIT.

package vsphere

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ApplyTKGConfigForVsphereHandlerFunc turns a function with the right signature into a apply t k g config for vsphere handler
type ApplyTKGConfigForVsphereHandlerFunc func(ApplyTKGConfigForVsphereParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ApplyTKGConfigForVsphereHandlerFunc) Handle(params ApplyTKGConfigForVsphereParams) middleware.Responder {
	return fn(params)
}

// ApplyTKGConfigForVsphereHandler interface for that can handle valid apply t k g config for vsphere params
type ApplyTKGConfigForVsphereHandler interface {
	Handle(ApplyTKGConfigForVsphereParams) middleware.Responder
}

// NewApplyTKGConfigForVsphere creates a new http.Handler for the apply t k g config for vsphere operation
func NewApplyTKGConfigForVsphere(ctx *middleware.Context, handler ApplyTKGConfigForVsphereHandler) *ApplyTKGConfigForVsphere {
	return &ApplyTKGConfigForVsphere{Context: ctx, Handler: handler}
}

/*ApplyTKGConfigForVsphere swagger:route POST /api/provider/vsphere/tkgconfig vsphere applyTKGConfigForVsphere

Apply changes to TKG configuration file for vSphere

*/
type ApplyTKGConfigForVsphere struct {
	Context *middleware.Context
	Handler ApplyTKGConfigForVsphereHandler
}

func (o *ApplyTKGConfigForVsphere) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewApplyTKGConfigForVsphereParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
