// Code generated by go-swagger; DO NOT EDIT.

package vsphere

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVsphereThumbprintHandlerFunc turns a function with the right signature into a get vsphere thumbprint handler
type GetVsphereThumbprintHandlerFunc func(GetVsphereThumbprintParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVsphereThumbprintHandlerFunc) Handle(params GetVsphereThumbprintParams) middleware.Responder {
	return fn(params)
}

// GetVsphereThumbprintHandler interface for that can handle valid get vsphere thumbprint params
type GetVsphereThumbprintHandler interface {
	Handle(GetVsphereThumbprintParams) middleware.Responder
}

// NewGetVsphereThumbprint creates a new http.Handler for the get vsphere thumbprint operation
func NewGetVsphereThumbprint(ctx *middleware.Context, handler GetVsphereThumbprintHandler) *GetVsphereThumbprint {
	return &GetVsphereThumbprint{Context: ctx, Handler: handler}
}

/* GetVsphereThumbprint swagger:route GET /api/providers/vsphere/thumbprint vsphere getVsphereThumbprint

Get vSphere thumbprint

*/
type GetVsphereThumbprint struct {
	Context *middleware.Context
	Handler GetVsphereThumbprintHandler
}

func (o *GetVsphereThumbprint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVsphereThumbprintParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
