export const AZURE_MC_BASIC_TAB_NAMES = ['Azure Credentials', 'Cluster Settings'];

/* eslint-disable no-unused-vars */
export const enum AZURE_FIELDS {
    CLUSTER_NAME = 'CLUSTER_NAME',
    NODE_PROFILE = 'NODE_PROFILE',
    TENANT_ID = 'TENANT_ID',
    CLIENT_ID = 'CLIENT_ID',
    CLIENT_SECRET = 'CLIENT_SECRET',
    SUBSCRIPTION_ID = 'SUBSCRIPTION_ID',
    AZURE_ENVIRONMENT = 'AZURE_ENVIRONMENT',
    REGION = 'REGION',
    SSH_PUBLIC_KEY = 'SSH_PUBLIC_KEY',
    IMAGE_INFO = 'IMAGE_INFO',
}

export const enum AZURE_NODE_PROFILE_NAMES {
    SINGLE_NODE = 'SINGLE_NODE',
    HIGH_AVAILABILITY = 'HIGH_AVAILABILITY',
    PRODUCTION_READY = 'PRODUCTION_READY',
}
