// Code generated by go-swagger; DO NOT EDIT.

package avi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAviServiceEngineGroupsHandlerFunc turns a function with the right signature into a get avi service engine groups handler
type GetAviServiceEngineGroupsHandlerFunc func(GetAviServiceEngineGroupsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAviServiceEngineGroupsHandlerFunc) Handle(params GetAviServiceEngineGroupsParams) middleware.Responder {
	return fn(params)
}

// GetAviServiceEngineGroupsHandler interface for that can handle valid get avi service engine groups params
type GetAviServiceEngineGroupsHandler interface {
	Handle(GetAviServiceEngineGroupsParams) middleware.Responder
}

// NewGetAviServiceEngineGroups creates a new http.Handler for the get avi service engine groups operation
func NewGetAviServiceEngineGroups(ctx *middleware.Context, handler GetAviServiceEngineGroupsHandler) *GetAviServiceEngineGroups {
	return &GetAviServiceEngineGroups{Context: ctx, Handler: handler}
}

/*GetAviServiceEngineGroups swagger:route GET /api/avi/serviceenginegroups avi getAviServiceEngineGroups

Retrieve Avi load balancer service engine groups

*/
type GetAviServiceEngineGroups struct {
	Context *middleware.Context
	Handler GetAviServiceEngineGroupsHandler
}

func (o *GetAviServiceEngineGroups) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAviServiceEngineGroupsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
