/* eslint-disable no-unused-vars */
export enum AZURE_FIELDS {
    CLUSTER_NAME = 'CLUSTER_NAME',
    INSTANCE_TYPE = 'INSTANCE_TYPE',
    TENANT_ID = 'TENANT_ID',
    CLIENT_ID = 'CLIENT_ID',
    CLIENT_SECRET = 'CLIENT_SECRET',
    SUBSCRIPTION_ID = 'SUBSCRIPTION_ID',
    AZURE_ENVIRONMENT = 'AZURE_ENVIRONMENT',
    REGION = 'REGION',
    SSH_PUBLIC_KEY = 'SSH_PUBLIC_KEY',
}
