export const enum UNMANAGED_CLUSTER_FIELDS {
    //BASIC FIELDS
    CLUSTER_NAME = 'CLUSTER_NAME',

    //ADVANCED FIELDS
    CONTROL_PLANE_NODE_COUNT = 'CONTROL_PLANE_NODE_COUNT',
    WORKER_NODE_COUNT = 'WORKER_NODE_COUNT',
    CLUSTER_PROVIDER = 'CLUSTER_PROVIDER',

    //NETWORK FIELDS
    CNI_PROVIDER = 'CNI_PROVIDER',
    CLUSTER_SERVICE_CIDR = 'CLUSTER_SERVICE_CIDR',
    CLUSTER_POD_CIDR = 'CLUSTER_POD_CIDR',
    IP_ADDRESS = 'IP_ADDRESS',
    NODE_PORT_MAPPING = 'NODE_PORT_MAPPING',
    HOST_PORT_MAPPING = 'HOST_PORT_MAPPING',
    CLUSTER_PROTOCOL = 'CLUSTER_PROTOCOL',
}
